%General Mission Analysis Tool(GMAT) Script
%Created: 2024-12-21 11:41:30


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft V2;
GMAT V2.DateFormat = A1Gregorian;
GMAT V2.Epoch = '29 Aug 1977 15:31:44.000';
GMAT V2.CoordinateSystem = SunMJ2000Eq;
GMAT V2.DisplayStateType = Cartesian;
GMAT V2.X = 140338129.195645;
GMAT V2.Y = -49650023.0373715;
GMAT V2.Z = -18769218.8181521;
GMAT V2.VX = 24.09673784;
GMAT V2.VY = 56.66190963;
GMAT V2.VZ = 30.74998819;
GMAT V2.DryMass = 850;
GMAT V2.Cd = 2.2;
GMAT V2.Cr = 1.8;
GMAT V2.DragArea = 15;
GMAT V2.SRPArea = 1;
GMAT V2.SPADDragScaleFactor = 1;
GMAT V2.SPADSRPScaleFactor = 1;
GMAT V2.AtmosDensityScaleFactor = 1;
GMAT V2.ExtendedMassPropertiesModel = 'None';
GMAT V2.NAIFId = -10000001;
GMAT V2.NAIFIdReferenceFrame = -9000001;
GMAT V2.OrbitColor = Red;
GMAT V2.TargetColor = Teal;
GMAT V2.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT V2.CdSigma = 1e+70;
GMAT V2.CrSigma = 1e+70;
GMAT V2.Id = 'SatId';
GMAT V2.Attitude = CoordinateSystemFixed;
GMAT V2.SPADSRPInterpolationMethod = Bilinear;
GMAT V2.SPADSRPScaleFactorSigma = 1e+70;
GMAT V2.SPADDragInterpolationMethod = Bilinear;
GMAT V2.SPADDragScaleFactorSigma = 1e+70;
GMAT V2.AtmosDensityScaleFactorSigma = 1e+70;
GMAT V2.ModelFile = 'aura.3ds';
GMAT V2.ModelOffsetX = 0;
GMAT V2.ModelOffsetY = 0;
GMAT V2.ModelOffsetZ = 0;
GMAT V2.ModelRotationX = 0;
GMAT V2.ModelRotationY = 0;
GMAT V2.ModelRotationZ = 0;
GMAT V2.ModelScale = 1;
GMAT V2.AttitudeDisplayStateType = 'Quaternion';
GMAT V2.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT V2.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT V2.EulerAngleSequence = '321';







%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 2700;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Coordinate Systems
%----------------------------------------

Create CoordinateSystem SunMJ2000Eq;
GMAT SunMJ2000Eq.Origin = Sun;
GMAT SunMJ2000Eq.Axes = MJ2000Eq;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0.4691275167785235 0.1536555142503098 ];
GMAT DefaultOrbitView.Size = [ 0.5167785234899329 0.5315985130111525 ];
GMAT DefaultOrbitView.RelativeZOrder = 49;
GMAT DefaultOrbitView.Maximized = false;
GMAT DefaultOrbitView.Add = {V2, Earth, Mars, Jupiter, Neptune, Saturn, Uranus, Sun};
GMAT DefaultOrbitView.CoordinateSystem = SunMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true true true true true true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Sun;
GMAT DefaultOrbitView.ViewPointVector = Jupiter;
GMAT DefaultOrbitView.ViewDirection = Sun;
GMAT DefaultOrbitView.ViewScaleFactor = 1.5;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = SunMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
GMAT DefaultGroundTrackPlot.SolverIterations = Current;
GMAT DefaultGroundTrackPlot.UpperLeft = [ 0.003355704697986577 0 ];
GMAT DefaultGroundTrackPlot.Size = [ 0.5 0.449814126394052 ];
GMAT DefaultGroundTrackPlot.RelativeZOrder = 40;
GMAT DefaultGroundTrackPlot.Maximized = false;
GMAT DefaultGroundTrackPlot.Add = {V2};
GMAT DefaultGroundTrackPlot.DataCollectFrequency = 1;
GMAT DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
GMAT DefaultGroundTrackPlot.NumPointsToRedraw = 0;
GMAT DefaultGroundTrackPlot.ShowPlot = true;
GMAT DefaultGroundTrackPlot.MaxPlotPoints = 20000;
GMAT DefaultGroundTrackPlot.CentralBody = Earth;
GMAT DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(V2) {V2.ElapsedDays = 365};
